# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90fe8357a454b0b8ebdb67d879a7387add1745b436807ac5f322153cee26824fca39f7be95df03be34a208e95ce37d581784142e69b26dc19fc932579b455c2f
  scripts_path: /home/bcc/rasouzas/Workspace/Megazord/scripts
  ldap_host: overwatch.linux.ime.usp.br
  ldap_port: 6002

staging:
  secret_key_base: 90fe8357a454b0b8ebdb67d879a7387add1745b436807ac5f322153cee26824fca39f7be95df03be34a208e95ce37d581784142e69b26dc19fc932579b455c2f
  scripts_path: /var/www/megazord/scripts
  ldap_host: overwatch.linux.ime.usp.br
  ldap_port: 6002

test:
  secret_key_base: 90fe8357a454b0b8ebdb67d879a7387add1745b436807ac5f322153cee26824fca39f7be95df03be34a208e95ce37d581784142e69b26dc19fc932579b455c2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  scripts_path: /var/www/megazord/scripts

